### ISSUE TITLE
Question about memory copy

### ISSUE THREAD

**Issue by temeddix** [Idein/msgpack-schema#32]
Hi! thank you for this awesome crate. I've been using `rmp_serde`, but the `msgpack!` macro of this crate is awesome.

I have one question. If we include the `Bin(vec![..])` in the `msgpack!` macro, does it get copied in memory, or is it zero-copy? I'm asking because the binary could be big, if it is something like a high-resolution image.

There's no discussions tab in this repo, so I thought I should ask here.

**Comment by umadein** [comment]
Hi! @temeddix 

I think `msgpack!` macro takes away borrowing and does not copy the value.

**Comment by temeddix** [comment]
@umadein Thanks!

**Comment by nyuichi** [comment]
closing as fixed
