### ISSUE TITLE
[Suggestion] Use `macro` to reduce duplicate code

### ISSUE THREAD

**Issue by hoangdt84** [Idein/msgpack-schema#50]
Hi @nyuichi,

Should we use `macro` for `impl Serialize` to reduce duplicate code? For example:
```
impl Serialize for u8 {
    fn serialize(&self, serializer: &mut Serializer) {
        serializer.serialize_int(Int::from(*self))
    }
}

impl Serialize for u16 {
    fn serialize(&self, serializer: &mut Serializer) {
        serializer.serialize_int(Int::from(*self))
    }
}
```

If you agree, I can send a PR.

**Comment by umadein** [comment]
Hi @hoangdt84 

Thank you for your suggestion!

But after talking with @nyuichi , we decided not to take that approach.
In this case, we think it is better to keep it simple than using macro to reduce the duplication of codes.

**Comment by hoangdt84** [comment]
Thanks for your reply :)

Of topic, do you have any plan to support `std::io::Write` trait in `Serializer`?
